parameters:
    sip_news.repository.new.class: SIP\NewsBundle\Repository\NewsRepository

services:
    sip_news.controller.news:
        class: %sip.news.controller.class%
        arguments: ["sip_news", "new", "SIPNewsBundle:News"]
        calls:
            - [ setContainer, [ @service_container ] ]

    sip_news.manager.news:
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getClassMetadata
        class: Doctrine\ORM\Mapping\ClassMetadata
        public: false
        arguments: [%sip.news.model.class%]

    sip_news.repository.new:
        class: %sip_news.repository.new.class%
        arguments: [ @sylius_cart.manager.cart, @sip_news.manager.news ]