services:
    sip_news.controller.news:
        class: %sip.news.controller.class%
        arguments: ["sip_news", "new", "SIPNewsBundle:News"]
        calls:
            - [ setContainer, [ @service_container ] ]

    sip_news.default_entity_manager.news:
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getClassMetadata
        class: Doctrine\ORM\Mapping\ClassMetadata
        public: false
        arguments: [%sip.news.model.class%]

    sip_news.manager.news:
        alias: doctrine.orm.entity_manager

    sip_news.repository.new:
        class: %sip_news.repository.class%
        arguments: [ @sip_news.manager.news, @sip_news.default_entity_manager.news ]