admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

SIPUserBundle:
    resource: '@SIPUserBundle/Resources/config/routing/routing.yml'
    prefix:   /admin

SIPResourceBundle:
    resource: '@SIPResourceBundle/Resources/config/routing/routing.yml'
    prefix:   /

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

SIPTextBundle:
    resource: '@SIPTextBundle/Resources/config/routing.yml'
    prefix:   /

SIPAssortmentBundle:
    resource: '@SIPAssortmentBundle/Resources/config/routing.yml'
    prefix:   /
