parameters:
    sip.cart_item_resolver.class: SIP\CartBundle\Resolver\ItemResolver

services:
    sip.cart_item_resolver:
        class: %sip.cart_item_resolver.class%
        arguments: [@sylius.repository.product, @form.factory]

