parameters:
    sip.cart_item_resolver.class: SIP\CartBundle\Cart\ItemResolver

services:
    sip.cart_item_resolver:
        class: %sip.cart_item_resolver.class%
        arguments: [@doctrine.orm.entity_manager]

