parameters:
    sip.content.log.admin.class: SIP\ResourceBundle\Admin\ContentLogAdmin

services:
    sip.content.log.admin:
        class: %sip.content.log.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Log, label: ContentLog }
        arguments: [null, SIP\ResourceBundle\Entity\ContentLog, SonataAdminBundle:CRUD, @sonata.admin.pool]

    sip.content.cart.admin:
        class: SIP\ResourceBundle\Admin\CartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Cart, label: Cart }
        arguments: [null, SIP\ResourceBundle\Entity\Cart, SonataAdminBundle:CRUD]

    sip.content.cart_item.admin:
        class: SIP\ResourceBundle\Admin\CartItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Cart, label: CartItem }
        arguments: [null, SIP\ResourceBundle\Entity\CartItem, SonataAdminBundle:CRUD]

    sip.assortment.product.admin:
        class: SIP\ResourceBundle\Admin\Assortment\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Assortment, label: Product }
        arguments: [null, SIP\ResourceBundle\Entity\Assortment\Product, SonataAdminBundle:CRUD]

    sip.assortment.variant.admin:
        class: SIP\ResourceBundle\Admin\Assortment\VariantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Assortment, label: Variant }
        arguments: [null, SIP\ResourceBundle\Entity\Assortment\Variant, SonataAdminBundle:CRUD]

    sip.assortment.property.admin:
        class: SIP\ResourceBundle\Admin\Assortment\PropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Assortment, label: Property }
        arguments: [null, Sylius\Bundle\AssortmentBundle\Entity\Property\Property, SonataAdminBundle:CRUD]

    sip.assortment.option.admin:
        class: SIP\ResourceBundle\Admin\Assortment\OptionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Assortment, label: Option }
        arguments: [null, Sylius\Bundle\AssortmentBundle\Entity\Option\DefaultOption, SonataAdminBundle:CRUD]

    sip.assortment.value.admin:
        class: SIP\ResourceBundle\Admin\Assortment\ValueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Assortment, label: Value }
        arguments: [null, Sylius\Bundle\AssortmentBundle\Entity\Option\DefaultOptionValue, SonataAdminBundle:CRUD]