parameters:
    sip.content.log.admin.class: SIP\ResourceBundle\Admin\ContentLogAdmin

services:
    sip.content.log.admin:
        class: %sip.content.log.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Log, label: ContentLog }
        arguments: [null, SIP\ResourceBundle\Entity\ContentLog, SonataAdminBundle:CRUD, @sonata.admin.pool]

    sip.content.cart.admin:
        class: SIP\ResourceBundle\Admin\CartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Cart, label: Cart }
        arguments: [null, SIP\ResourceBundle\Entity\Cart, SonataAdminBundle:CRUD]

    sip.content.cart_item.admin:
        class: SIP\ResourceBundle\Admin\CartItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Cart, label: CartItem }
        arguments: [null, SIP\ResourceBundle\Entity\CartItem, SonataAdminBundle:CRUD]