parameters:
    sip.content.log.admin.class: SIP\ResourceBundle\Admin\ContentLogAdmin
    sip.content.cart.admin.class: SIP\ResourceBundle\Admin\CartAdmin
    sip.content.cart_item.admin.class: SIP\ResourceBundle\Admin\CartItemAdmin

services:
    sip.content.log.admin:
        class: %sip.content.log.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Log, label: ContentLog }
        arguments: [null, SIP\ResourceBundle\Entity\ContentLog, SonataAdminBundle:CRUD, @sonata.admin.pool]

    sip.content.cart.admin:
        class: %sip.content.cart.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Cart, label: Cart }
        arguments: [null, %sylius_cart.model.cart.class%, SonataAdminBundle:CRUD]

    sip.content.cart_item.admin:
        class: %sip.content.cart_item.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Cart, label: CartItem }
        arguments: [null, %sylius_cart.model.item.class%, SonataAdminBundle:CRUD]