sylius_cart:
    driver: doctrine/orm
    resolver: sip.cart_item_resolver
    classes:
        cart:
            model: SIP\CartBundle\Entity\Cart
        item:
            model: SIP\CartBundle\Entity\CartItem
            form:  SIP\CartBundle\Form\Type\CartItemType

sylius_assortment:
    driver: doctrine/orm
    classes:
        product:
            model: SIP\AssortmentBundle\Entity\Product
            controller: SIP\AssortmentBundle\Controller\ProductController
            repository: SIP\AssortmentBundle\Repository\ProductRepository
        variant:
            model: SIP\AssortmentBundle\Entity\Variant
        option:
            model: SIP\AssortmentBundle\Entity\Option
        property:
            model: SIP\AssortmentBundle\Entity\Property