sylius_cart:
    driver: doctrine/orm
    resolver: sip.cart_item_resolver
    classes:
        cart:
            model: SIP\ResourceBundle\Entity\Cart
        item:
            model: SIP\ResourceBundle\Entity\CartItem
            form: SIP\ResourceBundle\Form\Type\CartItemType

sylius_assortment:
    driver: doctrine/orm
    classes:
        product:
            model: SIP\AssortmentBundle\Entity\Product
            controller: SIP\AssortmentBundle\Controller\ProductController
        variant:
            model: SIP\AssortmentBundle\Entity\Variant
        option:
            model: SIP\AssortmentBundle\Entity\Option
        property:
            model: SIP\AssortmentBundle\Entity\Property