parameters:
    sip_assortment.form.type.option_value.class: SIP\AssortmentBundle\Form\Type\OptionValueType
    sip_assortment.product.manager.class: SIP\AssortmentBundle\Manager\ProductManager

services:
    sip_assortment.form.type.option_value:
        class: %sip_assortment.form.type.option_value.class%
        tags:
            - { name: form.type, alias: option_value }
        calls:
            - [ setContainer, [ @service_container ] ]
