parameters:
#    sip_assortment.example.class: SIP\AssortmentBundle\Example

services:
#    sip_assortment.example:
#        class: %sip_assortment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
