sip_assortment_variant_option:
    pattern:  /_sys/varion_option
    defaults: { _controller: SIPAssortmentBundle:VariantAdmin:variantOption }

sip_assortment_product_list:
    pattern: /product
    defaults:
        _controller: sylius.controller.product:indexAction
        _template: SIPAssortmentBundle:Product:list.html.twig
        _paginate: 9
        _criteria:
            disabled: 0

sip_assortment_product_show:
    pattern: /product/{slug}
    defaults:
        _controller: sylius.controller.product:showAction
        _template: SIPAssortmentBundle:Product:show.html.twig
        _identifier: slug

sip_assortment_product_list_by_category:
    pattern: /product/category/{slug}
    defaults:
        _controller: sylius.controller.product:listByCategoryAction
        _template: SIPAssortmentBundle:Product:list.html.twig
        _paginate: 9
        _criteria:
            disabled: 0